Sample/Controllers/OnlineStoreController.cs
using Sample.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace Sample.Controllers
{
    public class OnlineStoreController : Controller
    {
        OnlineStoreContext context;
        public OnlineStoreController(OnlineStoreContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var category = context.Categories.ToList();
           
            return View(category);
        }
        public IActionResult Browse(string category)
        {
            var categoryModel=context.Categories.Include("Products")
                .Where(c=>c.Name==category).ToList();

            return View(categoryModel);
        }
        public IActionResult Details(int id)
        {
            var item = context.Products.Where(p => p.ProductId == id)
                .Include("Category")
                .Include("Brand").ToList();
          
            return View(item);
        }
    }
}

Sample/Views/OnlineStore/Browse.cshtml
@model IEnumerable<Sample.Models.Category>
@{
    ViewBag.Title = "Browse";
}
<ul>
    @foreach(var c in Model)
    {
        @foreach (var i in c.Products)
        {
           <div>
               <div class="card border border-bottom border-dark" style="width:191px;height:281px;float:left;margin-right:15px;margin-bottom:20px;">
                    <img class="card-img-top" src="~/@i.ItemUrl" alt="@i.Title" style="width:190px;height:200px">
                     <div class="card-body" style="text-align:center">
                       <h8 class="card-title">@i.Title</h8>
                           <div style="text-align:center;margin-bottom:25px" >
                            <a href="#"style="width:50;height:fit-content;font-size:small" class="btn btn-dark"  onclick="location.href='@Url.Action("Details","OnlineStore",new{id=i.ProductId})'">DETAILS</a>
                           </div>
                     </div>
                </div
           </div>
        }
    }
</ul>

Sample/Views/OnlineStore/Details.cshtml
@model IEnumerable<Sample.Models.Product>
@{
    ViewBag.Title = "Details";
}
@foreach(var p in Model)
{
    <div class="container" style="align-content:center;text-align:center">
    <p>
        
        <img style="width:300px;height:380px" alt="@p.Title"
         src="~/@p.ItemUrl" />
    </p>
    <h5>@p.Title</h5>
        <div style="font-family: " Times New Roman", Times, serif;" id="item-details">
        <p>
                <label>Category:</label>
             @p.Category?.Name
         </p>
         <p>
          <label>Brand:</label>
          @p.Brand.Name
         </p>
         
         <p>
           <label>Price:</label>
           @String.Format("{0:F}",
           p.Price)
         </p>
         <div>
             <a href="#" class="btn btn-dark" onclick="location.href='@Url.Action("AddToCart",
           "ShoppingCarts", new { id = @p.ProductId })'">ADD TO CART</a>
         </div>
        </div>
    <div class="fb-comments" data-width="230" data-numposts="5"></div>
 </div>
} 

Sample/Views/OnlineStore/Index.cshtml
@model IEnumerable<Category>
@{
    ViewBag.Title = "Shop By Category";
}
<h2>Shop By Category</h2>

    @foreach(var category in Model)
    {
        <div>
           <div class="col">
                <div class="col" style="float:left">
                      <div class="card" style="width:220px;height:380px;float:left;margin-right:15px;margin-bottom:15px">
                          <img class="card-img-top" src="~/@category.Description" style="width:220px;height:350px">
                          <div class="card-body" style="align-content:center;text-align:center">
                          <h5 class="card-title">@category.Name</h5>
                             <a href="#" class="btn btn-dark" onclick="location.href='@Url.Action("Browse",new {category=category.Name})'">SHOW MORE</a>
                          </div>
                      </div>
                </div>
           </div>
        </div>
        
                   
    }